name: 'SonnarQube Code Analysis'
description: 'Review code using SonarQube'
inputs:
  host:
    description: "SonarQube Server URL"
    required: true
  token:
    description: "Sonarqube token"
    required: true
  projectKey:
    description: "Sonarqube project key. The default key will be 'owner-repository'."
    required: false
    default: ""
  projectName:
    description: "Sonarqube project name. The default name will be 'owner-repository'."
    required: false
    default: ""
  projectBaseDir:
    description: "Sonar project base dir. "
    required: false
    default: "."
  githubToken:
    description: "Github token. https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'radio'
  color: 'gray-dark'
